# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/target'
    contents: '*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -R $(Build.ArtifactStagingDirectory)'
  displayName: 'List files in ArtifactStagingDirectory'  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/maven-artifact.zip'
    replaceExistingArchive: true
  displayName: 'Create ZIP archive'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'maven-artifact'
    publishLocation: 'Container'